title: Security Research
description: My Personal Security Research
author: Nafiez
github: https://github.com/nafiez
about: Interested in x86 Reverse Engineering and Vulnerability Research.
disqus_shortname: nafiezresearch
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/khpcN6z__400x400.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/zeifan"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/nafiez"

share:
  twitter_username: zeifan
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://nafiez.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
